### ISSUE TITLE
pgdg.list on debian 12 

### ISSUE THREAD

**Issue by yu210148** [itiligent/GVM-Install#2]
Hi there,

Ran the script and all seemed to go well however I ended up with an invalid entry in /etc/apt/sources.list.d/pgdg.list on a fresh Debian 12. The line I ended up with in there was:

`deb http://apt.postgresql.org/pub/repos/apt -pgdg main`

which is invalid. changing it to read: 

`deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main`

seems to have fixed it. I'm not sure why it didn't pick up 'bookworm' to stick in front of the dash but I figured I'd report it.

kev.

**Comment by yu210148** [comment]
The issue appears to be on line 241 of gvm-build-from-source.sh. lsb_release -cs is failing with command not found. May want to apt-get install lsb-release prior to this in the script.

**Comment by itiligent** [comment]
Thanks for that Kevin.  I'm not sure how my Debian test mules already had lsb-release installed , as far Ias I remember they are vanilla + a full apt upgrade only.  My Bad! 
The fix is at line 241. (I placed it down there in keeping with the rest of the script's section by section dependency mapping approach for ease of change managment .)
